### ISSUE TITLE
AUR package is unable to create configuration file

### ISSUE THREAD

**Issue by BlobCodes** [hugopl/tijolo#3]
**Describe the bug**
After installing the IDE from the AUR, it first won't boot. The cause is a File::NotFoundError, because the folder the configuration file should be in (~/.config/tijolo) by default does not exist. Manual creation of the folder is necessary.

**To Reproduce**
1. Delete the ~/.config/tijolo folder or rename/move it
2. Try to start the IDE

**Expected behavior**
The app detects that the folder is missing and creates it

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - GTK Version: gtk3-1:3.24.22-1
 - Version: Initial release (0.1.0)

**Additional context**
Error log:
```
2020-08-15T21:56:53.948855Z   INFO - Error loading config file: Error opening file with mode 'r': '/home/blobcodes/.config/tijolo/tijolo.toml': No such file or directory, creating a new one.
2020-08-15T21:56:53.948952Z  FATAL - Error opening file with mode 'w': '/home/blobcodes/.config/tijolo/tijolo.toml': No such file or directory
Error opening file with mode 'w': '/home/blobcodes/.config/tijolo/tijolo.toml': No such file or directory (File::NotFoundError)
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???

```

**Comment by hugopl** [comment]
Fixed, thanks!
