### ISSUE TITLE
Feat. request: add editorconfig support

### ISSUE THREAD

**Issue by megatux** [hugopl/tijolo#5]
It would be nice, for a future release to add editorconfig support.
[Editorconfig spec](https://editorconfig.org/).

**Comment by hugopl** [comment]
I agree, and they have a C-library with nothing special, i.e. easy to use directly by Crystal.

**Comment by hugopl** [comment]
~Fixed~ Implemented in 44caf7dce53ab0c30a073c26ec7a40495ee99249.
