### ISSUE TITLE
Can't increase editor font size (Ctrl+"+" ?)

### ISSUE THREAD

**Issue by megatux** [hugopl/tijolo#7]
**Describe the bug**
Can't increase editor font size (Ctrl+"+" ?), only decrement works (Ctrl+"-")

**Expected behavior**
Increment font size

**Environment (please complete the following information):**
 - OS: Manjaro i3 edition, latest
 - GTK Version: 3.24.24
 - Version 0.4.1

**Additional context**
Installed from AUR

**Comment by hugopl** [comment]
What keyboard layout do you use?

Did you try to go to preferences and change:
```
increase_font_size = "<Ctrl>equal"
```
to
```
increase_font_size = "<Ctrl>plus"
```

On my keyboard layout, the `plus` character is generated by `<shift>equals`, so I put the default shortcut to `<shift>equals`. I don't know yet a safer way to be sure the will always be the same whatever keyboard layout.... now I realize the problem exists I gonna look forward to see how people solved this problem... but the workaround is to change the shortcut in the config file, (:hamburger: menu -> Preferences)

**Comment by hugopl** [comment]
Ah, BTW there's a config attribute to specify the font size, I'm not sure if when this issue was open such settings was already available.

**Comment by megatux** [comment]
Tried again, works now, so closing it, thx

**Comment by megatux** [comment]
Adding that setting line to the config. worked here

> increase_font_size = "<Ctrl>plus"

thanks
